name: build-deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
      
    - name: Build
      run: dotnet build Lincoln.Web/Lincoln.Web.csproj

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}
    
    - name: Push to Docker Hub
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64
        context: .
        file: ./Dockerfile
        push: true 
        tags: horvatic/lincoln:1.4